"""Initial migration

Revision ID: af27c5d5ed93
Revises: 
Create Date: 2025-11-30 11:43:22.518476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af27c5d5ed93'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feedback_entries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('predicted_label', sa.String(length=50), nullable=False),
    sa.Column('user_label', sa.String(length=50), nullable=True),
    sa.Column('scores', sa.JSON(), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_feedback_entries_id'), 'feedback_entries', ['id'], unique=False)
    op.create_table('prediction_records',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('label', sa.String(length=50), nullable=False),
    sa.Column('scores', sa.JSON(), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_prediction_records_id'), 'prediction_records', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_prediction_records_id'), table_name='prediction_records')
    op.drop_table('prediction_records')
    op.drop_index(op.f('ix_feedback_entries_id'), table_name='feedback_entries')
    op.drop_table('feedback_entries')
    # ### end Alembic commands ###
